//! Keep the published capability matrix aligned with the application's registry.
use mluva_core::feature_maturity::{CAPABILITIES, Maturity};
use std::{env, fmt::Write, fs, path::Path, process::ExitCode};

fn markdown() -> String {
    let mut output = concat!(
        "<!-- Generated by `make linux-feature-maturity`; do not edit by hand. -->\n\n",
        "# Feature maturity\n\n",
        "Omarchy is the primary platform: the core dictation, rewrite and widget workflow is tested end to end ",
        "and used daily by the maintainer. **Verified on Omarchy** identifies that working set. ",
        "**Experimental** features remain available with the limits below. Fedora GNOME compatibility ",
        "is retained, but has not been tested for several releases.\n\n",
        "Automatic paste is an explicit known limitation: it depends on the desktop and target application ",
        "and is disabled by default. Clipboard delivery is the standard workflow. Automated tests use ",
        "isolated sessions; platform acceptance comes from use on the actual desktop.\n\n",
    ).to_owned();
    for maturity in [Maturity::Verified, Maturity::Experimental] {
        writeln!(
            output,
            "## {}\n\n| Feature | Current boundary |\n| --- | --- |",
            maturity.label()
        )
        .unwrap();
        for capability in CAPABILITIES.iter().filter(|item| item.maturity == maturity) {
            writeln!(output, "| {} | {} |", capability.title, capability.summary).unwrap();
        }
        output.push('\n');
    }
    // The released generator joins one final empty line, yielding one trailing LF.
    output.pop();
    output
}

fn main() -> ExitCode {
    let arguments: Vec<_> = env::args_os().skip(1).collect();
    let usage = "Usage: mluva-feature-maturity (--check | --write)";
    if arguments.len() == 1 && matches!(arguments[0].to_str(), Some("--help" | "-h")) {
        println!("{usage}");
        return ExitCode::SUCCESS;
    }
    if arguments.len() != 1 || !matches!(arguments[0].to_str(), Some("--check" | "--write")) {
        eprintln!("{usage}");
        return ExitCode::from(2);
    }
    let output = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("docs/feature-maturity.md");
    let expected = markdown();
    if arguments[0] == "--write" {
        return match fs::write(output, expected) {
            Ok(()) => ExitCode::SUCCESS,
            Err(error) => {
                eprintln!("Cannot write docs/feature-maturity.md: {error}");
                ExitCode::FAILURE
            }
        };
    }
    if fs::read_to_string(output).is_ok_and(|current| current == expected) {
        ExitCode::SUCCESS
    } else {
        eprintln!("docs/feature-maturity.md is stale; run `make linux-feature-maturity`.");
        ExitCode::FAILURE
    }
}
